# -*- coding: utf-8 -*-
"""H20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17S7FcrVkGwT3_9sztXcSR33OqtSkUKtR
"""

!pip install h2o

!pip install pyforest

import pyforest

import h2o

h2o.init()

from h2o.automl import H2OAutoML

data = h2o.import_file('/content/drive/My Drive/cars_deploy.csv')

cars = h2o.H2OFrame(pd.DataFrame(data))

data.head()

data.types

data.describe()

data_train,data_test = data.split_frame(ratios=[.7])

data_test

y = "price"
x = data.columns
x.remove(y)



ml = H2OAutoML(max_models = 10, seed = 10, exclude_algos = ["StackedEnsemble", "DeepLearning"], verbosity="info", nfolds=5)

ml.train(x = x, y = y, training_frame = data_train)

leaderboard = ml.leaderboard

from h2o.estimators.gbm import H2OGradientBoostingEstimator

cars_gbm = H2OGradientBoostingEstimator(seed = 1234) 
cars_gbm.train(x = x,
               y = y,
               training_frame = data_train,)

cars_gbm.r2()

leaderboard.head()

data_pred=cars_gbm.predict(data_test)

data_pred.head()

cars_gbm.model_performance(data_test)

model_path = h2o.save_model(model=cars_gbm, path="/content/drive/My Drive/deployment-heroku", force=True)

my_local_model = h2o.download_model(model=cars_gbm, path="/content/drive/My Drive/deployment-heroku")